name: Test

on:
  - push
  - pull_request

jobs:
  build:
    strategy:
      matrix:
        rust-version: [1.60.0, stable, nightly]
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Rust ${{ matrix.rust-version }}
        uses: actions-rs/toolchain@v1
        id: rustup
        with:
          toolchain: ${{ matrix.rust-version }}
          override: true
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install fuse
        run: sudo apt-get install libfuse3-dev
      - name: Build
        run: |
          LOCK_SHA256=$(shasum -a 256 Cargo.lock)
          cargo build --verbose
          if [ $LOCK_SHA256 != $(shasum -a 256 Cargo.lock)]; then exit 1; fi
      - name: Run unit tests
        run: cargo test --verbose
      - name: Run integration test
        run: python3 test.py
      - name: Run fuzz test
        run: python3 fuzz.py
